const BOARD_SITUATIONS = [
  { text: 'AIRPORT CHECK-IN', location: 'NEW YORK' },
  { text: 'RENT AN APARTMENT', location: 'LONDON' },
  { text: 'ORDER AT A CAFE', location: 'TORONTO' },
  { text: 'BUY A SIM CARD', location: 'SYDNEY' },
  { text: 'INTRODUCE YOURSELF', location: 'BOSTON' },
  { text: 'VISIT THE DOCTOR', location: 'CHICAGO' },
  { text: 'MEET YOUR CLASSMATES', location: 'EDINBURGH' },
  { text: 'ASK FOR DIRECTIONS', location: 'MELBOURNE' },
];

const STRESS_LEVELS = [
  { min: 0,  max: 20,  emoji: '😰', text: "I'm scared to speak",       textRu: 'Боюсь говорить' },
  { min: 21, max: 40,  emoji: '😬', text: "A little nervous, honestly", textRu: 'Немного нервничаю, честно' },
  { min: 41, max: 60,  emoji: '😐', text: "I can manage basic things",  textRu: 'Справляюсь с базовым' },
  { min: 61, max: 80,  emoji: '🙂', text: "Getting more confident",     textRu: 'Становлюсь увереннее' },
  { min: 81, max: 100, emoji: '😎', text: "Ready for real practice",    textRu: 'Готов к настоящей практике' },
];

const SCENARIOS_BY_GOAL = {

  moving: [
    {
      id: 1,
      speaker: '👮',
      role: 'Border Control Officer',
      roleRu: 'Офицер пограничного контроля',
      question: 'What is the purpose of your visit?',
      context: "You've just arrived at passport control. The officer is looking at your documents and waiting for your answer.",
      contextRu: 'Ты только что подошёл к паспортному контролю. Офицер смотрит на документы и ждёт твоего ответа.',
      hint: '💡 Tip: Be specific and formal. Mention studying, work, or tourism.',
      hintRu: '💡 Совет: Будь конкретным и официальным. Назови цель визита.',
      feedback: {
        score: 'good',
        improved: "I'm here to study at [University] as part of a full-time degree program.",
        grammarNote: 'Use "I\'m here to" — it\'s the natural, native phrase. Avoid "I come for" or "I am come to".',
        grammarNoteRu: 'Используй "I\'m here to" — это естественная конструкция. Избегай "I come for" или "I am come to".',
        toneNote: 'Border officers want brief, confident answers. Name the institution if possible — it shows you\'re prepared.',
        toneNoteRu: 'Офицеры хотят кратких, уверенных ответов. Назови учреждение — это показывает, что ты подготовлен.',
        issues: ['grammar', 'informal'],
      },
    },
    {
      id: 2,
      speaker: '👮',
      role: 'Border Control Officer',
      roleRu: 'Офицер пограничного контроля',
      question: 'How long do you plan to stay?',
      context: 'The officer is reviewing your visa stamp and wants to confirm your stay duration.',
      contextRu: 'Офицер проверяет штамп твоей визы и хочет уточнить срок пребывания.',
      hint: '💡 Tip: Give a specific duration. Match it to your visa.',
      hintRu: '💡 Совет: Назови конкретный срок. Он должен совпадать с визой.',
      feedback: {
        score: 'great',
        improved: "I'll be staying for one year. I have a student visa valid until [date].",
        grammarNote: '"I\'ll be staying" is the correct future continuous — shows a planned, ongoing situation.',
        grammarNoteRu: '"I\'ll be staying" — правильное будущее длительное время, показывает запланированную ситуацию.',
        toneNote: 'Mentioning the visa type proactively shows you\'re organized and confident. Officers appreciate it.',
        toneNoteRu: 'Проактивное упоминание типа визы показывает организованность и уверенность. Офицеры это ценят.',
        issues: [],
      },
    },
    {
      id: 3,
      speaker: '🏠',
      role: 'Landlord',
      roleRu: 'Арендодатель',
      question: 'So, what exactly are you looking for in a flat?',
      context: "You've arranged a viewing for an apartment. The landlord wants to understand your needs before showing you around.",
      contextRu: 'Ты пришёл на просмотр квартиры. Арендодатель хочет понять твои требования перед показом.',
      hint: '💡 Tip: Mention budget, location preference, and how long you need it.',
      hintRu: '💡 Совет: Назови бюджет, предпочтения по расположению и срок аренды.',
      feedback: {
        score: 'good',
        improved: "I'm looking for a one-bedroom flat, ideally close to public transport. My budget is around [X] per month, and I'd need it from [date] for at least a year.",
        grammarNote: '"I\'m looking for" — use the present continuous for ongoing searches. Not "I search" or "I look for".',
        grammarNoteRu: '"I\'m looking for" — используй Present Continuous для текущего поиска. Не "I search" или "I look for".',
        toneNote: 'Being specific about budget and dates shows you\'re a serious tenant. Vague answers waste everyone\'s time.',
        toneNoteRu: 'Конкретика по бюджету и срокам показывает серьёзность намерений. Расплывчатость раздражает арендодателей.',
        issues: ['grammar'],
      },
    },
    {
      id: 4,
      speaker: '📱',
      role: 'Mobile Store Assistant',
      roleRu: 'Консультант в магазине связи',
      question: 'Hi there, what can I help you with today?',
      context: "You're at a phone shop. You need a local SIM card with a data plan so you can use maps and messaging apps.",
      contextRu: 'Ты в магазине связи. Тебе нужна местная SIM-карта с интернетом для карт и мессенджеров.',
      hint: '💡 Tip: Say you need a SIM, mention data (not just calls), and ask about the options.',
      hintRu: '💡 Совет: Скажи, что нужна SIM, уточни, что важен интернет, и попроси показать варианты.',
      feedback: {
        score: 'great',
        improved: "Hi, I'd like to get a local SIM card with a decent data plan — mainly for maps and WhatsApp. What prepaid options do you have?",
        grammarNote: '"I\'d like to get" is polite and natural. "I want a SIM" works but sounds abrupt in a shop context.',
        grammarNoteRu: '"I\'d like to get" — вежливо и естественно. "I want a SIM" понятно, но звучит резковато.',
        toneNote: 'Explaining WHY you need data ("maps, WhatsApp") helps the assistant recommend the right plan faster.',
        toneNoteRu: 'Объяснение цели ("карты, WhatsApp") помогает консультанту быстрее подобрать нужный тариф.',
        issues: [],
      },
    },
  ],

  study: [
    {
      id: 1,
      speaker: '👩‍💼',
      role: 'Admin Office Staff',
      roleRu: 'Сотрудник деканата',
      question: 'Can I help you? Do you have an appointment?',
      context: "First day at university. You're at the admin office trying to register and collect your student ID.",
      contextRu: 'Первый день в университете. Ты в деканате — нужно зарегистрироваться и получить студенческий билет.',
      hint: '💡 Tip: State your name, that you\'re a new student, and what you need.',
      hintRu: '💡 Совет: Назови имя, скажи что ты новый студент и что тебе нужно.',
      feedback: {
        score: 'good',
        improved: "Hi, I'm a new international student — I'm here to complete my registration and pick up my student ID. My name is [Name].",
        grammarNote: '"I\'m here to" + verb is the natural phrase for stating your purpose at an office. Avoid "I come to register".',
        grammarNoteRu: '"I\'m here to" + глагол — естественная конструкция для объяснения цели визита. Не "I come to register".',
        toneNote: 'Lead with "new international student" — it tells staff exactly which process applies to you and speeds things up.',
        toneNoteRu: 'Начни с "new international student" — это сразу объясняет, какая процедура тебя касается.',
        issues: ['grammar'],
      },
    },
    {
      id: 2,
      speaker: '👨‍🏫',
      role: 'Professor',
      roleRu: 'Преподаватель',
      question: 'What seems to be the problem with the assignment?',
      context: "Office hours. You're confused about the essay prompt and haven't started yet. The deadline is in three days.",
      contextRu: 'Офисные часы преподавателя. Тебе непонятно задание для эссе, а дедлайн через три дня.',
      hint: '💡 Tip: Be specific about what\'s unclear. Say what you\'ve tried or read already.',
      hintRu: '💡 Совет: Чётко скажи что именно непонятно. Упомяни что уже пробовал сделать.',
      feedback: {
        score: 'good',
        improved: "I've read the brief a few times, but I'm not sure what you mean by 'critically evaluate' — should I focus on one argument or compare several perspectives?",
        grammarNote: '"I\'m not sure what you mean by..." is a precise, polite way to ask for clarification. Avoid "I don\'t understand the task".',
        grammarNoteRu: '"I\'m not sure what you mean by..." — точный и вежливый способ уточнить. Избегай "I don\'t understand the task".',
        toneNote: 'Showing you\'ve already tried ("I\'ve read it a few times") signals effort. Professors respond better to specific questions than "I\'m confused".',
        toneNoteRu: 'Упомянув, что уже читал задание, ты показываешь старание. Преподаватели лучше реагируют на конкретные вопросы.',
        issues: ['grammar'],
      },
    },
    {
      id: 3,
      speaker: '🧑‍🎓',
      role: 'Classmate',
      roleRu: 'Однокурсник',
      question: 'Hey, is this your first semester here? Where are you from?',
      context: "Five minutes before class starts. You're sitting next to someone new who wants to chat.",
      contextRu: 'До начала лекции пять минут. Рядом сел незнакомый студент и хочет поговорить.',
      hint: '💡 Tip: Short, friendly answer. Then ask something back to keep the conversation alive.',
      hintRu: '💡 Совет: Краткий, дружелюбный ответ. Потом задай встречный вопрос.',
      feedback: {
        score: 'great',
        improved: "Yeah, first semester! I'm from [Country]. Still finding my way around — this campus is huge. What about you, have you been here long?",
        grammarNote: '"Still finding my way around" is a natural idiom for being new somewhere. "Still" + present continuous works perfectly here.',
        grammarNoteRu: '"Still finding my way around" — идиома для ситуации новичка. "Still" + Present Continuous работает отлично.',
        toneNote: 'Ending with a question ("What about you?") is the key to small talk. It shows interest and keeps the conversation going naturally.',
        toneNoteRu: 'Встречный вопрос в конце — главный приём светской беседы. Он показывает интерес и не даёт разговору заглохнуть.',
        issues: [],
      },
    },
    {
      id: 4,
      speaker: '📚',
      role: 'University Librarian',
      roleRu: 'Библиотекарь',
      question: 'Do you have your student card to register for borrowing?',
      context: "You need library access to download journal articles, but your student card hasn't arrived yet.",
      contextRu: 'Тебе нужен доступ к библиотеке для статей, но студенческий билет ещё не выдали.',
      hint: '💡 Tip: Explain your situation calmly. Ask if there\'s a temporary solution.',
      hintRu: '💡 Совет: Спокойно объясни ситуацию. Спроси, есть ли временное решение.',
      feedback: {
        score: 'great',
        improved: "I don't have my student card yet — I only registered yesterday. Is there a temporary guest pass or could you register me with my student number for now?",
        grammarNote: '"I don\'t have it yet" uses "yet" correctly — it implies you expect to have it soon. Very natural in this context.',
        grammarNoteRu: '"I don\'t have it yet" — "yet" здесь правильно, оно подразумевает, что карта скоро будет. Очень естественно.',
        toneNote: 'Offering alternatives ("guest pass OR student number") shows problem-solving initiative and usually gets a faster yes.',
        toneNoteRu: 'Предложить альтернативы самому ("гостевой пропуск ИЛИ номер студента") ускоряет решение.',
        issues: [],
      },
    },
  ],

  work: [
    {
      id: 1,
      speaker: '👔',
      role: 'Team Manager',
      roleRu: 'Руководитель команды',
      question: "Everyone, let's welcome our new colleague. Would you like to say a few words?",
      context: "First day. The whole team is gathered in the meeting room for a quick welcome. All eyes are on you.",
      contextRu: 'Первый день. Вся команда собралась в переговорке. Все смотрят на тебя.',
      hint: '💡 Tip: Name, where you\'re from, your role, one thing you\'re excited about. Under a minute.',
      hintRu: '💡 Совет: Имя, откуда ты, твоя роль, одна вещь, которая тебя радует. До минуты.',
      feedback: {
        score: 'good',
        improved: "Hi everyone, I'm [Name], joining as [role]. I've been working in [field] for [X] years and I'm really looking forward to working with you all — feel free to say hi anytime!",
        grammarNote: '"I\'ve been working" (present perfect continuous) is the correct form for experience up to now. Not "I worked" or "I am working for X years".',
        grammarNoteRu: '"I\'ve been working" (Present Perfect Continuous) — правильная форма для опыта "до сего момента". Не "I worked for X years".',
        toneNote: '"Feel free to say hi anytime" ends on a warm, approachable note. Small invitations like this build rapport fast in English-speaking offices.',
        toneNoteRu: '"Feel free to say hi" завершает знакомство тепло. Такие маленькие приглашения быстро налаживают контакт.',
        issues: ['tense'],
      },
    },
    {
      id: 2,
      speaker: '☕',
      role: 'Colleague',
      roleRu: 'Коллега',
      question: "Hi! How are you settling in? Have you found everything okay?",
      context: "Second day, coffee machine area. A colleague you haven't met properly starts chatting.",
      contextRu: 'Второй день, кофемашина. Коллега, с которым ещё не познакомился, начинает разговор.',
      hint: '💡 Tip: Be honest but positive. Then ask something back.',
      hintRu: '💡 Совет: Честно, но позитивно. Потом задай встречный вопрос.',
      feedback: {
        score: 'great',
        improved: "Pretty well, thanks! Still getting used to the systems, but everyone's been really helpful. How long have you been on the team?",
        grammarNote: '"Still getting used to" is the natural phrase for being in adjustment mode. "Get used to" + noun/gerund — not "get used to do".',
        grammarNoteRu: '"Still getting used to" — естественная фраза для периода адаптации. "Get used to" + существительное/герундий, не инфинитив.',
        toneNote: 'Saying "everyone\'s been really helpful" is a safe, positive statement that builds goodwill. Complaining on day two — even if true — damages first impressions.',
        toneNoteRu: '"Все очень помогают" — безопасный позитивный ответ. Жалобы на второй день портят первое впечатление.',
        issues: [],
      },
    },
    {
      id: 3,
      speaker: '📊',
      role: 'Project Lead',
      roleRu: 'Руководитель проекта',
      question: "Do you have any questions about the project brief?",
      context: "End of a kickoff meeting. You have two things you didn't fully follow — one about the timeline, one about who owns what.",
      contextRu: 'Конец вводного митинга. Два момента остались непонятными — сроки и распределение ответственности.',
      hint: '💡 Tip: Ask one specific question at a time. Use "Could you clarify..." or "I wasn\'t clear on...".',
      hintRu: '💡 Совет: По одному вопросу за раз. Используй "Could you clarify..." или "I wasn\'t clear on...".',
      feedback: {
        score: 'good',
        improved: "Yes, a couple of things — could you clarify the deadline for the first milestone? And I wasn't clear on who owns the client communication — is that with you or the account team?",
        grammarNote: '"I wasn\'t clear on" is a natural, non-blaming way to flag confusion. "I don\'t understand" is too blunt in a professional setting.',
        grammarNoteRu: '"I wasn\'t clear on" — вежливый способ обозначить непонимание. "I don\'t understand" звучит слишком резко в рабочей среде.',
        toneNote: 'Asking two specific questions (not five) shows you\'ve prioritized. Ending with "is that X or Y?" makes it easy to answer.',
        toneNoteRu: 'Два конкретных вопроса (не пять) показывают приоритеты. Финальное "X или Y?" упрощает ответ.',
        issues: ['grammar'],
      },
    },
    {
      id: 4,
      speaker: '📋',
      role: 'Manager',
      roleRu: 'Менеджер',
      question: "Can you give me a quick status update on your tasks?",
      context: "Friday afternoon check-in. You've finished two tasks, one is in progress, and one is blocked waiting for someone else.",
      contextRu: 'Пятничный check-in. Два задания готовы, одно в процессе, одно заблокировано из-за другого человека.',
      hint: '💡 Tip: Done → In progress → Blocked. Name the blocker clearly so action can be taken.',
      hintRu: '💡 Совет: Готово → В процессе → Заблокировано. Назови блокер, чтобы можно было действовать.',
      feedback: {
        score: 'great',
        improved: "Sure — the report and the client slides are done. The data analysis is about 70% complete, should be ready Monday. And the integration is blocked — I'm waiting on API access from the dev team.",
        grammarNote: '"Should be ready" expresses confident expectation — more professional than "will be maybe ready" or "I think I finish".',
        grammarNoteRu: '"Should be ready" выражает уверенное ожидание — профессиональнее, чем "will be maybe ready" или "I think I finish".',
        toneNote: 'The "Done → In progress → Blocked" structure is the standard in English-speaking teams. It\'s fast, clear, and shows you\'re on top of things.',
        toneNoteRu: 'Структура "Готово → В процессе → Заблокировано" — стандарт в англоязычных командах. Чётко и по делу.',
        issues: [],
      },
    },
  ],

  travel: [
    {
      id: 1,
      speaker: '🏨',
      role: 'Hotel Receptionist',
      roleRu: 'Администратор отеля',
      question: 'Welcome! Do you have a reservation with us?',
      context: "You've arrived at your hotel after a long journey. You booked online two weeks ago.",
      contextRu: 'Ты приехал в отель после долгой дороги. Бронировал онлайн две недели назад.',
      hint: '💡 Tip: Give your name and booking details. It\'s fine to ask about check-out time or breakfast here.',
      hintRu: '💡 Совет: Назови имя и детали брони. Здесь же можно спросить про выезд или завтрак.',
      feedback: {
        score: 'great',
        improved: "Yes, I have a reservation under [Name] — it should be for three nights from tonight. Could you also let me know what time breakfast is served?",
        grammarNote: '"Under [Name]" is the standard phrase for hotel bookings. "In the name of" also works but is more formal.',
        grammarNoteRu: '"Under [Name]" — стандартная фраза для бронирования. "In the name of" тоже работает, но звучит официальнее.',
        toneNote: 'Confirming the number of nights prevents mix-ups. Asking about breakfast at check-in saves a separate trip to the desk later.',
        toneNoteRu: 'Подтверждение количества ночей предотвращает ошибки. Вопрос про завтрак сразу при заселении экономит время.',
        issues: [],
      },
    },
    {
      id: 2,
      speaker: '🍽️',
      role: 'Waiter',
      roleRu: 'Официант',
      question: "Are you ready to order, or do you need a few more minutes?",
      context: "You're at a restaurant. One dish caught your eye but you're not sure what it contains — you don't eat meat.",
      contextRu: 'Ты в ресторане. Одно блюдо приглянулось, но непонятно из чего — ты не ешь мясо.',
      hint: '💡 Tip: Ask what\'s in the dish before committing. Polite and completely normal.',
      hintRu: '💡 Совет: Уточни состав перед тем как заказать. Это вежливо и совершенно нормально.',
      feedback: {
        score: 'great',
        improved: "Almost — could you tell me what's in the pasta with mushrooms? I don't eat meat, so I just want to check.",
        grammarNote: '"Could you tell me what\'s in..." is an indirect question — the word order after "what" stays normal (subject + verb), not inverted.',
        grammarNoteRu: '"Could you tell me what\'s in..." — косвенный вопрос. После "what" порядок слов прямой (подлежащее + сказуемое), не инвертированный.',
        toneNote: 'Adding "I don\'t eat meat, so I just want to check" gives context without making it a big deal. Matter-of-fact tone works best for dietary questions.',
        toneNoteRu: 'Краткое объяснение ("I don\'t eat meat") даёт контекст без лишней драмы. Нейтральный тон лучше всего работает при уточнении состава.',
        issues: [],
      },
    },
    {
      id: 3,
      speaker: '🚶',
      role: 'Passer-by',
      roleRu: 'Прохожий',
      question: "Sure, where are you trying to get to?",
      context: "You stopped someone on the street. You need the nearest metro station — you've been walking for 20 minutes.",
      contextRu: 'Ты остановил прохожего. Нужна ближайшая станция метро — идёшь уже 20 минут.',
      hint: '💡 Tip: State destination clearly. Ask if it\'s walkable or if you need transport.',
      hintRu: '💡 Совет: Чётко назови цель. Спроси, можно ли дойти пешком или нужен транспорт.',
      feedback: {
        score: 'good',
        improved: "I'm trying to find the nearest metro station. Is it within walking distance from here, or should I take a bus?",
        grammarNote: '"Within walking distance" is a key travel phrase. "Can I walk there?" also works perfectly.',
        grammarNoteRu: '"Within walking distance" — ключевая туристическая фраза. "Can I walk there?" тоже отлично работает.',
        toneNote: 'Giving two options ("walk or bus?") makes it easy for the person to answer quickly. Open-ended "how do I get there?" can produce a very long answer.',
        toneNoteRu: 'Два варианта в вопросе ("пешком или автобус?") помогают получить быстрый ответ. Открытое "как добраться?" может вызвать длинное объяснение.',
        issues: ['grammar'],
      },
    },
    {
      id: 4,
      speaker: '🛍️',
      role: 'Shop Assistant',
      roleRu: 'Продавец-консультант',
      question: "Can I help you find something?",
      context: "Clothing store. You want a jacket like the one in the window display but in a different colour and larger size.",
      contextRu: 'Магазин одежды. Хочешь куртку как на витрине, но другого цвета и большего размера.',
      hint: '💡 Tip: Point to or describe the item. Say the size and colour you want.',
      hintRu: '💡 Совет: Покажи или опиши вещь. Назови размер и цвет.',
      feedback: {
        score: 'great',
        improved: "Yes please — I'm interested in that jacket in the window. Do you have it in navy or black, in a large?",
        grammarNote: '"Do you have it in [colour], in [size]?" is the standard shopping phrase. Both "in a large" and "in size large" are correct.',
        grammarNoteRu: '"Do you have it in [цвет], in [размер]?" — стандартная фраза для магазина. "In a large" и "in size large" оба правильны.',
        toneNote: '"Yes please" before your request sounds engaged and polite. "I\'m interested in" is softer than "I want" — useful when you might need to try before buying.',
        toneNoteRu: '"Yes please" перед запросом звучит вежливо. "I\'m interested in" мягче, чем "I want" — полезно когда нужно примерить перед покупкой.',
        issues: [],
      },
    },
  ],
};

const DASHBOARD_BY_GOAL = {
  moving: {
    missionTitle: 'Airport Survival',
    missionTitleRu: 'Выживание в аэропорту',
    missionDesc: "You've just landed. Here's what's going to happen next — and what to say.",
    missionDescRu: 'Ты только что приземлился. Вот что произойдёт дальше — и что говорить.',
    situations: [
      { icon: '✈️', title: 'Check-in & boarding',    titleRu: 'Регистрация на рейс',    min: 5, level: 'beginner' },
      { icon: '👮', title: 'Passport control',         titleRu: 'Паспортный контроль',    min: 4, level: 'beginner' },
      { icon: '🏠', title: 'Rent an apartment',        titleRu: 'Снять квартиру',         min: 8, level: 'intermediate' },
      { icon: '📱', title: 'Get a SIM card',           titleRu: 'Купить SIM-карту',       min: 3, level: 'beginner' },
    ],
  },
  study: {
    missionTitle: 'Campus First Day',
    missionTitleRu: 'Первый день в кампусе',
    missionDesc: "Your first day at university. Navigate admin, meet your advisor, get settled.",
    missionDescRu: 'Первый день в университете. Деканат, куратор, общежитие.',
    situations: [
      { icon: '🏫', title: 'Admin office check-in',   titleRu: 'Регистрация в деканате',  min: 6, level: 'beginner' },
      { icon: '👥', title: 'Meet classmates',          titleRu: 'Познакомиться с группой', min: 4, level: 'beginner' },
      { icon: '📚', title: 'Ask a professor',          titleRu: 'Вопрос преподавателю',    min: 5, level: 'intermediate' },
      { icon: '🏠', title: 'Dorm check-in',            titleRu: 'Заселение в общежитие',   min: 7, level: 'beginner' },
    ],
  },
  work: {
    missionTitle: 'Office First Day',
    missionTitleRu: 'Первый день в офисе',
    missionDesc: "Starting at a new company. Introductions, small talk, and your first meeting.",
    missionDescRu: 'Начало в новой компании. Знакомства, светская беседа и первая встреча.',
    situations: [
      { icon: '🤝', title: 'Introduce yourself',      titleRu: 'Представиться команде',   min: 5, level: 'beginner' },
      { icon: '🏢', title: 'Meet your manager',       titleRu: 'Встреча с менеджером',    min: 6, level: 'intermediate' },
      { icon: '💬', title: 'Office small talk',       titleRu: 'Светская беседа в офисе', min: 4, level: 'beginner' },
      { icon: '📧', title: 'Write a work email',      titleRu: 'Деловое письмо',          min: 8, level: 'intermediate' },
    ],
  },
  travel: {
    missionTitle: 'Hotel Check-in',
    missionTitleRu: 'Заселение в отель',
    missionDesc: "You've arrived. Navigate hotel check-in and your first evening abroad.",
    missionDescRu: 'Ты добрался. Заселение в отель и первый вечер.',
    situations: [
      { icon: '🏨', title: 'Hotel check-in',          titleRu: 'Заселение в отель',       min: 4, level: 'beginner' },
      { icon: '🍔', title: 'Order at a cafe',         titleRu: 'Заказать в кафе',         min: 5, level: 'beginner' },
      { icon: '🗺️', title: 'Ask for directions',     titleRu: 'Спросить дорогу',         min: 3, level: 'beginner' },
      { icon: '🛍️', title: 'Shop at a store',        titleRu: 'Покупки в магазине',      min: 6, level: 'intermediate' },
    ],
  },
};

const PLAN_ITEMS_BY_GOAL = {
  moving: [
    { icon: '✈️', label: '<strong>Day 1–2:</strong> Airport & first hours',          labelRu: '<strong>День 1–2:</strong> Аэропорт и первые часы' },
    { icon: '🏠', label: '<strong>Day 3–4:</strong> Housing & neighborhood basics',   labelRu: '<strong>День 3–4:</strong> Жильё и район' },
    { icon: '🧾', label: '<strong>Day 5–6:</strong> Documents, SIM card, bank',       labelRu: '<strong>День 5–6:</strong> Документы, SIM-карта, банк' },
    { icon: '💬', label: '<strong>Day 7:</strong> Small talk & meeting people',       labelRu: '<strong>День 7:</strong> Светская беседа и знакомства' },
  ],
  study: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & arrival',                labelRu: '<strong>День 1:</strong> Аэропорт и прибытие' },
    { icon: '🏫', label: '<strong>Day 2–3:</strong> Campus, admin office, registration', labelRu: '<strong>День 2–3:</strong> Кампус, деканат, регистрация' },
    { icon: '👥', label: '<strong>Day 4–5:</strong> Meeting classmates & professors', labelRu: '<strong>День 4–5:</strong> Однокурсники и преподаватели' },
    { icon: '🍔', label: '<strong>Day 6–7:</strong> Everyday life & social English',  labelRu: '<strong>День 6–7:</strong> Быт и разговорный английский' },
  ],
  work: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & transit',                labelRu: '<strong>День 1:</strong> Аэропорт и транзит' },
    { icon: '🏢', label: '<strong>Day 2–3:</strong> Office intro, meetings, small talk', labelRu: '<strong>День 2–3:</strong> Офис, встречи, светская беседа' },
    { icon: '💬', label: '<strong>Day 4–5:</strong> Networking & professional English', labelRu: '<strong>День 4–5:</strong> Нетворкинг и деловой английский' },
    { icon: '🏠', label: '<strong>Day 6–7:</strong> Life admin & community',          labelRu: '<strong>День 6–7:</strong> Быт и комьюнити' },
  ],
  travel: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & hotel check-in',         labelRu: '<strong>День 1:</strong> Аэропорт и заселение в отель' },
    { icon: '🍔', label: '<strong>Day 2–3:</strong> Restaurants, cafes, ordering',   labelRu: '<strong>День 2–3:</strong> Рестораны, кафе, заказы' },
    { icon: '🗺️', label: '<strong>Day 4–5:</strong> Directions, transport, sightseeing', labelRu: '<strong>День 4–5:</strong> Маршруты, транспорт, достопримечательности' },
    { icon: '🛍️', label: '<strong>Day 6–7:</strong> Shopping & emergency phrases',   labelRu: '<strong>День 6–7:</strong> Шоппинг и экстренные фразы' },
  ],
};
