const BOARD_SITUATIONS = [
  { text: 'AIRPORT CHECK-IN', location: 'NEW YORK' },
  { text: 'RENT AN APARTMENT', location: 'LONDON' },
  { text: 'ORDER AT A CAFE', location: 'TORONTO' },
  { text: 'BUY A SIM CARD', location: 'SYDNEY' },
  { text: 'INTRODUCE YOURSELF', location: 'BOSTON' },
  { text: 'VISIT THE DOCTOR', location: 'CHICAGO' },
  { text: 'MEET YOUR CLASSMATES', location: 'EDINBURGH' },
  { text: 'ASK FOR DIRECTIONS', location: 'MELBOURNE' },
];

const STRESS_LEVELS = [
  { min: 0,  max: 20,  emoji: '😰', text: "I'm scared to speak",       textRu: 'Боюсь говорить' },
  { min: 21, max: 40,  emoji: '😬', text: "A little nervous, honestly", textRu: 'Немного нервничаю, честно' },
  { min: 41, max: 60,  emoji: '😐', text: "I can manage basic things",  textRu: 'Справляюсь с базовым' },
  { min: 61, max: 80,  emoji: '🙂', text: "Getting more confident",     textRu: 'Становлюсь увереннее' },
  { min: 81, max: 100, emoji: '😎', text: "Ready for real practice",    textRu: 'Готов к настоящей практике' },
];

const AIRPORT_SCENARIOS = [
  {
    id: 1,
    speaker: '👮',
    role: 'Border Control Officer',
    roleRu: 'Офицер пограничного контроля',
    question: 'What is the purpose of your visit?',
    context: "You've just arrived at passport control. The officer is looking at your documents and waiting for your answer.",
    contextRu: 'Ты только что подошёл к паспортному контролю. Офицер смотрит на документы и ждёт твоего ответа.',
    hint: '💡 Tip: Be specific and formal. Mention studying, work, or tourism.',
    hintRu: '💡 Совет: Будь конкретным и официальным. Назови цель визита.',
    sampleAnswer: "I'm here to study for a short-term academic program.",
    feedback: {
      score: 'good',
      improved: "I'm here to study at [University] as part of a full-time degree program.",
      grammarNote: 'Use "I\'m here to" — it\'s the natural, native phrase. Avoid "I come for" or "I am come to".',
      grammarNoteRu: 'Используй "I\'m here to" — это естественная конструкция. Избегай "I come for" или "I am come to".',
      toneNote: 'Border officers want brief, confident answers. Name the institution if possible — it shows you\'re prepared.',
      toneNoteRu: 'Офицеры хотят кратких, уверенных ответов. Назови учреждение — это показывает, что ты подготовлен.',
      issues: ['grammar', 'informal'],
    },
  },
  {
    id: 2,
    speaker: '👮',
    role: 'Border Control Officer',
    roleRu: 'Офицер пограничного контроля',
    question: 'How long do you plan to stay?',
    context: 'The officer is reviewing your visa stamp and wants to confirm your stay duration.',
    contextRu: 'Офицер проверяет штамп твоей визы и хочет уточнить срок пребывания.',
    hint: '💡 Tip: Give a specific duration. Match it to your visa.',
    hintRu: '💡 Совет: Назови конкретный срок. Он должен совпадать с визой.',
    sampleAnswer: "I'll be staying for approximately one year on a student visa.",
    feedback: {
      score: 'great',
      improved: "I'll be staying for one year. I have a student visa valid until [date].",
      grammarNote: '"I\'ll be staying" is the correct future continuous — shows a planned, ongoing situation.',
      grammarNoteRu: '"I\'ll be staying" — правильное будущее длительное время, показывает запланированную ситуацию.',
      toneNote: 'Mentioning the visa type proactively shows you\'re organized and confident. Officers appreciate it.',
      toneNoteRu: 'Проактивное упоминание типа визы показывает организованность и уверенность. Офицеры это ценят.',
      issues: [],
    },
  },
  {
    id: 3,
    speaker: '👮',
    role: 'Border Control Officer',
    roleRu: 'Офицер пограничного контроля',
    question: 'Do you have accommodation arranged?',
    context: "The officer wants to know where you'll be living. Have your address or dorm name ready.",
    contextRu: 'Офицер хочет знать, где ты будешь жить. Подготовь адрес или название общежития.',
    hint: '💡 Tip: Yes/No + a brief detail. Name the place if you can.',
    hintRu: '💡 Совет: Да/Нет + краткая деталь. Назови место если можешь.',
    sampleAnswer: 'Yes, I\'m staying at university accommodation in the city center.',
    feedback: {
      score: 'great',
      improved: "Yes, I have accommodation confirmed — I'll be at [Name] student residence.",
      grammarNote: '"I have accommodation confirmed" is more formal and natural than "I have accommodation arranged".',
      grammarNoteRu: '"I have accommodation confirmed" звучит более официально и естественно, чем "arranged".',
      toneNote: 'Give a specific name or address if you have it. Vague answers can cause delays.',
      toneNoteRu: 'Назови конкретное место или адрес. Расплывчатые ответы могут замедлить прохождение контроля.',
      issues: [],
    },
  },
  {
    id: 4,
    speaker: '✈️',
    role: 'Check-in Agent',
    roleRu: 'Агент регистрации',
    question: "Could I see your passport and booking confirmation?",
    context: "You're at the check-in counter. The agent needs your documents before issuing your boarding pass.",
    contextRu: 'Ты у стойки регистрации. Агент просит документы перед выдачей посадочного талона.',
    hint: '💡 Tip: Respond calmly and hand over documents. You can ask about luggage here.',
    hintRu: '💡 Совет: Ответь спокойно и передай документы. Здесь можно спросить о багаже.',
    sampleAnswer: "Of course, here you are. Could I also check my luggage allowance?",
    feedback: {
      score: 'great',
      improved: "Of course, here you are. Could you also confirm how many bags I can check in?",
      grammarNote: '"Here you are" is the standard polite phrase when handing something. "Could you confirm..." sounds more natural.',
      grammarNoteRu: '"Here you are" — стандартная вежливая фраза при передаче чего-либо. "Could you confirm..." звучит естественнее.',
      toneNote: 'Adding a follow-up question in one turn is smart — you save time and sound confident.',
      toneNoteRu: 'Задать уточняющий вопрос в одном ответе умно — экономишь время и звучишь уверенно.',
      issues: [],
    },
  },
];

const PLAN_ITEMS_BY_GOAL = {
  moving: [
    { icon: '✈️', label: '<strong>Day 1–2:</strong> Airport & first hours',          labelRu: '<strong>День 1–2:</strong> Аэропорт и первые часы' },
    { icon: '🏠', label: '<strong>Day 3–4:</strong> Housing & neighborhood basics',   labelRu: '<strong>День 3–4:</strong> Жильё и район' },
    { icon: '🧾', label: '<strong>Day 5–6:</strong> Documents, SIM card, bank',       labelRu: '<strong>День 5–6:</strong> Документы, SIM-карта, банк' },
    { icon: '💬', label: '<strong>Day 7:</strong> Small talk & meeting people',       labelRu: '<strong>День 7:</strong> Светская беседа и знакомства' },
  ],
  study: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & arrival',                labelRu: '<strong>День 1:</strong> Аэропорт и прибытие' },
    { icon: '🏫', label: '<strong>Day 2–3:</strong> Campus, admin office, registration', labelRu: '<strong>День 2–3:</strong> Кампус, деканат, регистрация' },
    { icon: '👥', label: '<strong>Day 4–5:</strong> Meeting classmates & professors', labelRu: '<strong>День 4–5:</strong> Однокурсники и преподаватели' },
    { icon: '🍔', label: '<strong>Day 6–7:</strong> Everyday life & social English',  labelRu: '<strong>День 6–7:</strong> Быт и разговорный английский' },
  ],
  work: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & transit',                labelRu: '<strong>День 1:</strong> Аэропорт и транзит' },
    { icon: '🏢', label: '<strong>Day 2–3:</strong> Office intro, meetings, small talk', labelRu: '<strong>День 2–3:</strong> Офис, встречи, светская беседа' },
    { icon: '💬', label: '<strong>Day 4–5:</strong> Networking & professional English', labelRu: '<strong>День 4–5:</strong> Нетворкинг и деловой английский' },
    { icon: '🏠', label: '<strong>Day 6–7:</strong> Life admin & community',          labelRu: '<strong>День 6–7:</strong> Быт и комьюнити' },
  ],
  travel: [
    { icon: '✈️', label: '<strong>Day 1:</strong> Airport & hotel check-in',         labelRu: '<strong>День 1:</strong> Аэропорт и заселение в отель' },
    { icon: '🍔', label: '<strong>Day 2–3:</strong> Restaurants, cafes, ordering',   labelRu: '<strong>День 2–3:</strong> Рестораны, кафе, заказы' },
    { icon: '🗺️', label: '<strong>Day 4–5:</strong> Directions, transport, sightseeing', labelRu: '<strong>День 4–5:</strong> Маршруты, транспорт, достопримечательности' },
    { icon: '🛍️', label: '<strong>Day 6–7:</strong> Shopping & emergency phrases',   labelRu: '<strong>День 6–7:</strong> Шоппинг и экстренные фразы' },
  ],
};
